"""Optional, bounded SQL front end. Only approved trees leave the child.

The child never opens a database. SQLGlot is a parser, not a security boundary.
All executable SQL is subsequently generated by sqlite_executor.Compiler.
"""
from __future__ import annotations
import json
import os
from pathlib import Path
import subprocess
import sys
import time

VERSION = '27.28.1'
MODE = 'sqlite-sql-text-v1'
MAX_BYTES = 16384
CPU_SECONDS = 3


def contract():
    return dict(mode=MODE, parser='sqlglot', version=VERSION, license='MIT',
                max_bytes=MAX_BYTES, max_ast_nodes=400, max_ast_depth=32,
                cpu_seconds=CPU_SECONDS, memory_bytes=268435456,
                lowering='bc-sqlite-lowering-v1', executable_output='bc-select-tree-v1')


def _lower(text, objects):
    """Child-only parser/lowering. No optimizer, transpiler, or SQL execution."""
    import sqlglot
    from sqlglot import exp as e
    from sqlglot.dialects.sqlite import SQLite
    from restricted_artifacts.sqlite_executor import compile_select, identifier, FUNCTIONS
    if sqlglot.__version__ != VERSION:
        raise ImportError('Parser version mismatch')
    class RestrictedSQLite(SQLite):
        class Parser(SQLite.Parser):
            # Keep spelling/arity, including invalid arity, rather than invoking
            # SQLGlot's function rewrites or SQLite's implicit ON TRUE rewrite.
            FUNCTIONS = {}
            FUNCTION_PARSERS = {}
            ADD_JOIN_ON_TRUE = False
    if not isinstance(text, str) or not text or len(text.encode()) > MAX_BYTES or '\0' in text:
        raise ValueError('size')
    dialect = RestrictedSQLite()
    from sqlglot.tokens import TokenType
    tokens = dialect.tokenize(text)
    if len(tokens) > 4096 or any(t.token_type in (TokenType.TOP, TokenType.FETCH) for t in tokens):
        raise ValueError('unsupported dialect or token limit')
    parsed = dialect.parse(text)
    if len(parsed) == 2 and type(parsed[-1]) is e.Semicolon and parsed[-1].comments and not parsed[-1].args:
        parsed.pop()  # Comment attached to the single optional terminal semicolon.
    if len(parsed) != 1 or not isinstance(parsed[0], e.Select):
        raise ValueError('statement')
    pending = [(parsed[0], 0)]
    count = 0
    while pending:
        node, depth = pending.pop()
        count += 1
        if count > 400 or depth > 32:
            raise ValueError('complexity')
        pending.extend((child, depth+1) for child in node.iter_expressions())

    def fields(node, allowed):
        if any(key not in allowed and val is not None and val is not False and val != []
               for key, val in node.args.items()):
            raise ValueError('unsupported modifier')
    def ident(node):
        if type(node) is not e.Identifier:
            raise ValueError('identifier')
        fields(node, {'this', 'quoted'})
        identifier(node.this)
        return node.this
    binary = {e.Add: '+', e.Sub: '-', e.Mul: '*', e.Div: '/', e.Mod: '%',
              e.EQ: '=', e.NEQ: '!=', e.LT: '<', e.LTE: '<=', e.GT: '>', e.GTE: '>=',
              e.And: 'and', e.Or: 'or', e.Is: 'is', e.Like: 'like'}
    def expr(node):
        kind = type(node)
        if kind is e.Paren:
            fields(node, {'this'})
            return expr(node.this)
        if kind is e.Column:
            fields(node, {'this', 'table'})
            return {'column': (ident(node.args['table'])+'.' if node.args.get('table') else '')+ident(node.this)}
        if kind is e.Literal:
            fields(node, {'this', 'is_string'})
            value = node.this if node.is_string else float(node.this) if any(c in node.this.lower() for c in '.e') else int(node.this)
            return {'literal': value}
        if kind is e.Null:
            fields(node, set())
            return {'literal': None}
        if kind is e.Neg and type(node.this) is e.Literal and not node.this.is_string:
            fields(node, {'this'})
            return {'literal': -expr(node.this)['literal']}
        if kind in binary:
            # SQLite dialect annotates division; these flags describe native
            # SQLite division, they do not cause a rewrite.
            allowed = {'this', 'expression'}
            if kind is e.Div:
                allowed |= {'typed', 'safe'}
                if node.args.get('typed') is not True or node.args.get('safe') is not True:
                    raise ValueError('division dialect')
            fields(node, allowed)
            return {'binary': [binary[kind], expr(node.this), expr(node.expression)]}
        if kind is e.Not and type(node.this) is e.Is:
            fields(node, {'this'})
            fields(node.this, {'this', 'expression'})
            return {'binary': ['is not', expr(node.this.this), expr(node.this.expression)]}
        if kind is e.Anonymous:
            fields(node, {'this', 'expressions'})
            name = node.this.lower() if isinstance(node.this, str) else ident(node.this).lower()
            if name not in FUNCTIONS:
                raise ValueError('function')
            args = node.expressions
            distinct = len(args) == 1 and type(args[0]) is e.Distinct
            if name == 'count' and len(args) == 1 and type(args[0]) is e.Star:
                fields(args[0], set())
                args = []  # SQLite COUNT() and COUNT(*) count the same rows.
            if distinct:
                fields(args[0], {'expressions'})
                args = args[0].expressions
            return {'call': {'name': name, 'args': [expr(a) for a in args], **({'distinct': True} if distinct else {})}}
        if kind is e.Case:
            fields(node, {'ifs', 'default'})  # searched CASE only
            pairs = []
            for branch in node.args['ifs']:
                if type(branch) is not e.If:
                    raise ValueError('case')
                fields(branch, {'this', 'true'})
                pairs.append([expr(branch.this), expr(branch.args['true'])])
            if node.args.get('default') is None:
                raise ValueError('explicit ELSE required')
            return {'case': {'when': pairs, 'else': expr(node.args['default'])}}
        if kind is e.Subquery:
            fields(node, {'this'})
            return {'select': select(node.this)}
        raise ValueError('unsupported expression')
    def source(node):
        if type(node) not in (e.Table, e.Subquery):
            raise ValueError('source')
        fields(node, {'this', 'alias'})
        result = {'table': ident(node.this)} if type(node) is e.Table else {'select': select(node.this)}
        alias = node.args.get('alias')
        if alias:
            if type(alias) is not e.TableAlias:
                raise ValueError('alias')
            fields(alias, {'this'})
            result['as'] = ident(alias.this)
        return result
    def select(node):
        if type(node) is not e.Select:
            raise ValueError('select')
        fields(node, {'expressions', 'from', 'joins', 'where', 'group', 'having', 'order', 'distinct', 'limit'})
        cols = []
        for item in node.expressions:
            if type(item) is e.Alias:
                fields(item, {'this', 'alias'})
                cols.append({'expr': expr(item.this), 'as': ident(item.args['alias'])})
            else:
                if type(item) is not e.Column:
                    raise ValueError('computed output requires explicit alias')
                cols.append({'expr': expr(item)})
        result = {'columns': cols}
        if node.args.get('from'):
            f = node.args['from']
            fields(f, {'this'})
            result['from'] = source(f.this)
        if node.args.get('distinct'):
            fields(node.args['distinct'], set())
            result['distinct'] = True
        joins = []
        for j in node.args.get('joins', []):
            fields(j, {'this', 'side', 'kind', 'on'})
            side, kind = j.args.get('side', ''), j.args.get('kind', '')
            if side not in ('', 'LEFT') or kind not in ('', 'INNER', 'CROSS', 'OUTER') or (kind == 'OUTER' and side != 'LEFT') or (side and kind in ('CROSS', 'INNER')):
                raise ValueError('join')
            join = {'kind': 'left' if side else 'cross' if kind == 'CROSS' else 'inner', 'source': source(j.this)}
            if j.args.get('on'):
                join['on'] = expr(j.args['on'])
            joins.append(join)
        if joins:
            result['joins'] = joins
        for key, target in [('where', 'where'), ('having', 'having')]:
            if node.args.get(key):
                fields(node.args[key], {'this'})
                result[target] = expr(node.args[key].this)
        if node.args.get('group'):
            fields(node.args['group'], {'expressions'})
            result['group_by'] = [expr(x) for x in node.args['group'].expressions]
        if node.args.get('order'):
            fields(node.args['order'], {'expressions'})
            order = []
            for x in node.args['order'].expressions:
                fields(x, {'this', 'desc', 'nulls_first'})
                desc = bool(x.args.get('desc'))
                if bool(x.args.get('nulls_first')) != (not desc):
                    raise ValueError('nondefault NULL ordering')
                order.append({'expr': expr(x.this), 'direction': 'desc' if desc else 'asc'})
            result['order_by'] = order
        if node.args.get('limit'):
            fields(node.args['limit'], {'expression'})
            limit = expr(node.args['limit'].expression)
            if set(limit) != {'literal'} or type(limit['literal']) is not int:
                raise ValueError('limit')
            result['limit'] = limit['literal']
        return result
    tree = select(parsed[0])
    compile_select(tree, objects)  # Authoritative existing bounds and object set.
    return tree


def lower(text, objects):
    """Bounded separate CPU process, no inherited credentials or working files."""
    start = time.monotonic()
    request = {'text': text, 'objects': sorted(objects)}
    if not isinstance(text, str) or len(text.encode()) > MAX_BYTES or len(json.dumps(request)) > 131072:
        return {'status': 'rejected', 'category': 'sql_input_limit', 'contract': contract()}
    try:
        result = subprocess.run([sys.executable, '-I', str(Path(__file__).resolve()), '--child'],
            input=json.dumps(request), text=True, capture_output=True, timeout=8,
            cwd='/tmp', env={'PATH': '/usr/bin:/bin', 'LANG': 'C.UTF-8'})
        report = json.loads(result.stdout) if result.returncode == 0 else {'status': 'rejected', 'category': 'sql_compiler_limit'}
    except subprocess.TimeoutExpired:
        report = {'status': 'rejected', 'category': 'sql_compiler_limit'}
    report.update(contract=contract(), wall_seconds=time.monotonic()-start)
    return report


if __name__ == '__main__':
    # Fixed trusted child entry point. No untrusted import paths or Python code.
    import resource
    resource.setrlimit(resource.RLIMIT_CPU, (CPU_SECONDS, CPU_SECONDS))
    resource.setrlimit(resource.RLIMIT_AS, (268435456, 268435456))
    resource.setrlimit(resource.RLIMIT_FSIZE, (0, 0))
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    start = time.process_time()
    try:
        request = json.loads(sys.stdin.read(131073))
        tree = _lower(request['text'], request['objects'])
        report = {'status': 'ok', 'tree': tree}
    except ImportError:
        report = {'status': 'blocked_prerequisite', 'category': 'pinned_parser_unavailable'}
    except Exception as exc:
        category = ('sql_parse_rejected' if type(exc).__module__ == 'sqlglot.errors' else
                    'sql_ir_rejected' if type(exc).__name__ == 'SQLRejected' else 'sql_construction_rejected')
        report = {'status': 'rejected', 'category': category}
    report['cpu_seconds'] = time.process_time()-start
    print(json.dumps(report))

